### ISSUE TITLE
add plugin to Alcatraz

### ISSUE THREAD

**Issue by dimohamdy** [dbgrandi/GoOutside#1]
@dbgrandi  great plugin but add it to Alcatraz
https://github.com/dimohamdy/Alcatraz#i-want-to-submit-my-package

**Comment by dimohamdy** [comment]
please accept the pull request

**Comment by dbgrandi** [comment]
Thanks! Looks good.

I've added myself as a watcher to https://github.com/alcatraz/alcatraz-packages/pull/520 and can merge this in once it's actually in Alcatraz so the README makes sense.

**Comment by dbgrandi** [comment]
(Oops, wrong issue.)

**Comment by dbgrandi** [comment]
Done. And documented in https://github.com/dbgrandi/GoOutside/pull/2
