### ISSUE TITLE
Seconds, minutes and hours

### ISSUE THREAD

**Issue by lfarah** [dbgrandi/GoOutside#3]
The plugin should format the time properly, following this:

``` swift
var seconds = 103
var minutes = 0
var hours = 0
while seconds >0
{
     if seconds > 60
     {
        minutes += 1
        seconds -= 60
     }
     if minutes > 60
     {
       hours += 1
       minutes -=60
     }
}
```

> Your builds took 1 minute and 42 seconds build

instead of

> Your build took 103 seconds

**Comment by DaidoujiChen** [comment]
Hello,

How about

``` swift
var seconds = 103
var minutes = 0
var hours = 0

minutes = seconds / 60
seconds %= 60

hours = minutes / 60
minutes %= 60
```

**Comment by lfarah** [comment]
yeah!

**Comment by dbgrandi** [comment]
Sounds like a great idea. Would gladly accept a pull request if anybody wants to tackle this.

If the goal is to get textual output, there are some edge cases that could be interesting.

```
61 seconds = "1 minute, 1 second" // singular minute
120 seconds = "2 minutes" // don't show empty seconds
4367 seconds = "1 hour, 12 minutes, 47 seconds"
```

**Comment by dbgrandi** [comment]
Implemented in https://github.com/dbgrandi/GoOutside/pull/4

![screen shot 2016-03-25 at 9 45 33 am](https://cloud.githubusercontent.com/assets/4033/14045204/6f987af8-f26e-11e5-8eee-63b4ab7f14bb.png)
