### ISSUE TITLE
Last Build Time

### ISSUE THREAD

**Issue by mohamede1945** [dbgrandi/GoOutside#6]
Nice work for this amazing plugin! Nice idea too :)

I would love to see the build time of the last run along with the total time that you show now.

Ideally, it would be great if we could have a chart showing the progress build time of the project over time.

**Comment by dbgrandi** [comment]
Excellent idea. I'm not actively working on this, but if you want to send a PR, I'll review it and help get it deployed.

**Comment by justinvallely** [comment]
@dbgrandi Thank you, this is great. Along with @mohamede1945's suggestions, I would love to have a way to reset the timer. Right now I'm assuming I can uninstall/reinstall.

@mohamede1945 You can view individual build time by running the terminal command listed in here: http://stackoverflow.com/questions/1027923/how-to-enable-build-timing-in-xcode

**Comment by mohamede1945** [comment]
@justinvallely Thank you so much! This is very useful.

**Comment by dbgrandi** [comment]
Closing because Xcode no longer plays nice with plugins.
