### ISSUE TITLE
Clean and restart counter

### ISSUE THREAD

**Issue by sagarkasture** [dbgrandi/GoOutside#7]
How do I restart the counter at any point? Currenly only way that seems to be possible is uninstall and install again.

**Comment by dbgrandi** [comment]
At the moment, that's the only method. If you want to add a reset button to the stats window, I'd merge that into the next release.

**Comment by sagarkasture** [comment]
That would be really great. So that people can measure time spend between specific interval. Say, I will reset it every monday morning so that I know how much time is spent at the end of week.
